---
- name: play level variables
  hosts: local
  connection: local
  vars:
   course: devops
   duration: 10hrs
   trainer: manoj

  tasks:
   - name: print course information
     ansible.builtin.debug:
      msg: "course {{ course }}, total duration {{ duration }}, trainer is {{ trainer }}"

  tasks: 
   - name: print information again
     ansible.builtin.debug:
      msg: "trainer is {{ trainer }}, taking the course {{ course }}, and total duration is {{ duration }}"